# Generated by Django 4.0.6 on 2022-07-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/')),
                ('icon', models.FileField(upload_to='features/')),
                ('icon_background', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=256)),
                ('author_designation', models.CharField(max_length=256)),
                ('testimonial_logo', models.FileField(upload_to='features/')),
            ],
        ),
    ]
