# Generated by Django 4.0.6 on 2022-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_feature_icon_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video/')),
                ('title', models.CharField(max_length=256)),
                ('logo', models.FileField(upload_to='video/')),
            ],
            options={
                'db_table': 'web_video',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='feature',
            table='web_feature',
        ),
    ]
