# Generated by Django 4.0.6 on 2022-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_video_alter_feature_options_alter_feature_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='bg_image',
        ),
        migrations.AddField(
            model_name='video',
            name='play_image',
            field=models.ImageField(blank=True, null=True, upload_to='video/'),
        ),
    ]
