# Generated by Django 4.0.6 on 2022-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_image_video_bg_image_video_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='play_image',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
