# Generated by Django 4.0.6 on 2022-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_video_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='play_image',
            field=models.FileField(upload_to='video/'),
        ),
    ]
