# Generated by Django 4.0.6 on 2022-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_marketingfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingfeature',
            name='image',
            field=models.FileField(upload_to='marketing/'),
        ),
    ]
