# Generated by Django 4.0.6 on 2022-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=256)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=256)),
            ],
            options={
                'db_table': 'web_blogs',
                'ordering': ['-id'],
            },
        ),
    ]
