# Generated by Django 4.0.6 on 2022-07-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_testimonial_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
    ]
