# Generated by Django 4.0.6 on 2022-07-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_blogs_options_remove_testimonial_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
    ]
