# Generated by Django 4.0.6 on 2022-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_brand_white_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hero_image',
            field=models.ImageField(default='a', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
