# Generated by Django 4.0.6 on 2022-07-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_products_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.products'),
            preserve_default=False,
        ),
    ]
